//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Mconfig.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="MconfigParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IMconfigListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="MconfigParser.file"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFile([NotNull] MconfigParser.FileContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MconfigParser.file"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFile([NotNull] MconfigParser.FileContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MconfigParser.record"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRecord([NotNull] MconfigParser.RecordContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MconfigParser.record"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRecord([NotNull] MconfigParser.RecordContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>TypeSelectorInfo</c>
	/// labeled alternative in <see cref="MconfigParser.sourceSelector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeSelectorInfo([NotNull] MconfigParser.TypeSelectorInfoContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>TypeSelectorInfo</c>
	/// labeled alternative in <see cref="MconfigParser.sourceSelector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeSelectorInfo([NotNull] MconfigParser.TypeSelectorInfoContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>AbsPathSelectorInfo</c>
	/// labeled alternative in <see cref="MconfigParser.sourceSelector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAbsPathSelectorInfo([NotNull] MconfigParser.AbsPathSelectorInfoContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>AbsPathSelectorInfo</c>
	/// labeled alternative in <see cref="MconfigParser.sourceSelector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAbsPathSelectorInfo([NotNull] MconfigParser.AbsPathSelectorInfoContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MconfigParser.typeSelector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeSelector([NotNull] MconfigParser.TypeSelectorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MconfigParser.typeSelector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeSelector([NotNull] MconfigParser.TypeSelectorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MconfigParser.absPathSelector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAbsPathSelector([NotNull] MconfigParser.AbsPathSelectorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MconfigParser.absPathSelector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAbsPathSelector([NotNull] MconfigParser.AbsPathSelectorContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>RegexTrendSelector</c>
	/// labeled alternative in <see cref="MconfigParser.trendSelector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRegexTrendSelector([NotNull] MconfigParser.RegexTrendSelectorContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>RegexTrendSelector</c>
	/// labeled alternative in <see cref="MconfigParser.trendSelector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRegexTrendSelector([NotNull] MconfigParser.RegexTrendSelectorContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>NameTrendSelector</c>
	/// labeled alternative in <see cref="MconfigParser.trendSelector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNameTrendSelector([NotNull] MconfigParser.NameTrendSelectorContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>NameTrendSelector</c>
	/// labeled alternative in <see cref="MconfigParser.trendSelector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNameTrendSelector([NotNull] MconfigParser.NameTrendSelectorContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>UnitTransform</c>
	/// labeled alternative in <see cref="MconfigParser.transform"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnitTransform([NotNull] MconfigParser.UnitTransformContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>UnitTransform</c>
	/// labeled alternative in <see cref="MconfigParser.transform"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnitTransform([NotNull] MconfigParser.UnitTransformContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ConvertTransform</c>
	/// labeled alternative in <see cref="MconfigParser.transform"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConvertTransform([NotNull] MconfigParser.ConvertTransformContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ConvertTransform</c>
	/// labeled alternative in <see cref="MconfigParser.transform"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConvertTransform([NotNull] MconfigParser.ConvertTransformContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>RenameTransform</c>
	/// labeled alternative in <see cref="MconfigParser.transform"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRenameTransform([NotNull] MconfigParser.RenameTransformContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>RenameTransform</c>
	/// labeled alternative in <see cref="MconfigParser.transform"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRenameTransform([NotNull] MconfigParser.RenameTransformContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ReplaceTransform</c>
	/// labeled alternative in <see cref="MconfigParser.transform"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReplaceTransform([NotNull] MconfigParser.ReplaceTransformContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ReplaceTransform</c>
	/// labeled alternative in <see cref="MconfigParser.transform"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReplaceTransform([NotNull] MconfigParser.ReplaceTransformContext context);
}
