//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Mconfig.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="MconfigParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IMconfigVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="MconfigParser.file"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFile([NotNull] MconfigParser.FileContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MconfigParser.record"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRecord([NotNull] MconfigParser.RecordContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>TypeSelectorInfo</c>
	/// labeled alternative in <see cref="MconfigParser.sourceSelector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeSelectorInfo([NotNull] MconfigParser.TypeSelectorInfoContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>AbsPathSelectorInfo</c>
	/// labeled alternative in <see cref="MconfigParser.sourceSelector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAbsPathSelectorInfo([NotNull] MconfigParser.AbsPathSelectorInfoContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MconfigParser.typeSelector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeSelector([NotNull] MconfigParser.TypeSelectorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MconfigParser.absPathSelector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAbsPathSelector([NotNull] MconfigParser.AbsPathSelectorContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>RegexTrendSelector</c>
	/// labeled alternative in <see cref="MconfigParser.trendSelector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRegexTrendSelector([NotNull] MconfigParser.RegexTrendSelectorContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>NameTrendSelector</c>
	/// labeled alternative in <see cref="MconfigParser.trendSelector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNameTrendSelector([NotNull] MconfigParser.NameTrendSelectorContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UnitTransform</c>
	/// labeled alternative in <see cref="MconfigParser.transform"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnitTransform([NotNull] MconfigParser.UnitTransformContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ConvertTransform</c>
	/// labeled alternative in <see cref="MconfigParser.transform"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConvertTransform([NotNull] MconfigParser.ConvertTransformContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>RenameTransform</c>
	/// labeled alternative in <see cref="MconfigParser.transform"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRenameTransform([NotNull] MconfigParser.RenameTransformContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ReplaceTransform</c>
	/// labeled alternative in <see cref="MconfigParser.transform"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReplaceTransform([NotNull] MconfigParser.ReplaceTransformContext context);
}
