//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Mconfig.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public partial class MconfigLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, STRING=9, 
		WS=10;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "T__1", "T__2", "T__3", "T__4", "T__5", "T__6", "T__7", "STRING", 
		"ESC", "WS"
	};


	public MconfigLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public MconfigLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'type'", "'absPath'", "'re'", "'name'", "'unit'", "'convert'", 
		"'rename'", "'replace'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, "STRING", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Mconfig.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static MconfigLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static int[] _serializedATN = {
		4,0,10,95,6,-1,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,6,
		2,7,7,7,2,8,7,8,2,9,7,9,2,10,7,10,1,0,1,0,1,0,1,0,1,0,1,1,1,1,1,1,1,1,
		1,1,1,1,1,1,1,1,1,2,1,2,1,2,1,3,1,3,1,3,1,3,1,3,1,4,1,4,1,4,1,4,1,4,1,
		5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,6,1,6,1,6,1,6,1,6,1,6,1,6,1,7,1,7,1,7,
		1,7,1,7,1,7,1,7,1,7,1,8,1,8,1,8,5,8,76,8,8,10,8,12,8,79,9,8,1,8,1,8,1,
		9,1,9,1,9,1,9,3,9,87,8,9,1,10,4,10,90,8,10,11,10,12,10,91,1,10,1,10,1,
		77,0,11,1,1,3,2,5,3,7,4,9,5,11,6,13,7,15,8,17,9,19,0,21,10,1,0,1,3,0,9,
		10,13,13,32,32,97,0,1,1,0,0,0,0,3,1,0,0,0,0,5,1,0,0,0,0,7,1,0,0,0,0,9,
		1,0,0,0,0,11,1,0,0,0,0,13,1,0,0,0,0,15,1,0,0,0,0,17,1,0,0,0,0,21,1,0,0,
		0,1,23,1,0,0,0,3,28,1,0,0,0,5,36,1,0,0,0,7,39,1,0,0,0,9,44,1,0,0,0,11,
		49,1,0,0,0,13,57,1,0,0,0,15,64,1,0,0,0,17,72,1,0,0,0,19,86,1,0,0,0,21,
		89,1,0,0,0,23,24,5,116,0,0,24,25,5,121,0,0,25,26,5,112,0,0,26,27,5,101,
		0,0,27,2,1,0,0,0,28,29,5,97,0,0,29,30,5,98,0,0,30,31,5,115,0,0,31,32,5,
		80,0,0,32,33,5,97,0,0,33,34,5,116,0,0,34,35,5,104,0,0,35,4,1,0,0,0,36,
		37,5,114,0,0,37,38,5,101,0,0,38,6,1,0,0,0,39,40,5,110,0,0,40,41,5,97,0,
		0,41,42,5,109,0,0,42,43,5,101,0,0,43,8,1,0,0,0,44,45,5,117,0,0,45,46,5,
		110,0,0,46,47,5,105,0,0,47,48,5,116,0,0,48,10,1,0,0,0,49,50,5,99,0,0,50,
		51,5,111,0,0,51,52,5,110,0,0,52,53,5,118,0,0,53,54,5,101,0,0,54,55,5,114,
		0,0,55,56,5,116,0,0,56,12,1,0,0,0,57,58,5,114,0,0,58,59,5,101,0,0,59,60,
		5,110,0,0,60,61,5,97,0,0,61,62,5,109,0,0,62,63,5,101,0,0,63,14,1,0,0,0,
		64,65,5,114,0,0,65,66,5,101,0,0,66,67,5,112,0,0,67,68,5,108,0,0,68,69,
		5,97,0,0,69,70,5,99,0,0,70,71,5,101,0,0,71,16,1,0,0,0,72,77,5,34,0,0,73,
		76,3,19,9,0,74,76,9,0,0,0,75,73,1,0,0,0,75,74,1,0,0,0,76,79,1,0,0,0,77,
		78,1,0,0,0,77,75,1,0,0,0,78,80,1,0,0,0,79,77,1,0,0,0,80,81,5,34,0,0,81,
		18,1,0,0,0,82,83,5,92,0,0,83,87,5,34,0,0,84,85,5,92,0,0,85,87,5,92,0,0,
		86,82,1,0,0,0,86,84,1,0,0,0,87,20,1,0,0,0,88,90,7,0,0,0,89,88,1,0,0,0,
		90,91,1,0,0,0,91,89,1,0,0,0,91,92,1,0,0,0,92,93,1,0,0,0,93,94,6,10,0,0,
		94,22,1,0,0,0,5,0,75,77,86,91,1,6,0,0
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
